# Generated by Django 3.2 on 2021-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=1000)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('chennai', models.BooleanField(default=False)),
                ('bangalore', models.BooleanField(default=False)),
                ('delhi', models.BooleanField(default=False)),
                ('covid', models.BooleanField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('budget', models.FloatField()),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
    ]
