# Generated by Django 3.2 on 2021-05-02 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customers',
            name='jaipur',
            field=models.BooleanField(default=False),
        ),
    ]
